services:
  postgres:
    image: postgres:18
    container_name: pf-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: puddle_farm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: pf-redis
    ports:
      - "6379:6379"

  # docker compose -f docker/docker-compose.dev.yml run --rm diesel migration run
  diesel:
    build: ./diesel
    container_name: pf-diesel
    profiles: ["tools"]
    environment:
      DATABASE_URL: postgresql://user:password@postgres/puddle_farm
    volumes:
      - ../migrations:/app/migrations
    working_dir: /app
    depends_on:
      - postgres

volumes:
  pgdata:
